---
title: "Results"
author: "Loong Kuan"
date: "16 September 2016"
params:
  result.folder: "elecNormNew"
  subset.length: 1
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(params$result.folder, "_", params$subset.length,'.html'))})
---

```{r setup, echo = FALSE}
options(width=80)
knitr::opts_chunk$set(echo = FALSE, out.width='750px', dpi=200)
library(knitr)
library(ggplot2)
library(ggrepel)
library(reshape2)
library(gridExtra)
library(grid)
library(foreign)
library(plotly)
read_chunk("../drift_timeline/plot.R")
```


Plotting for attribute subset of length:
```{r length}
print(params$subset.length)
```
For data set:
``` {r dataset}
print(params$result.folder)
```
<drift_timeline>
```{r plot}
folder <- paste0("../../data_out/", params$result.folder, "/stream")
PlotAllWindowSizes("COVARIATE", params$subset.length, folder, c())
PlotAllWindowSizes("JOINT", params$subset.length, folder, c())
PlotAllWindowSizes("LIKELIHOOD", params$subset.length, folder, c())
PlotAllWindowSizes("POSTERIOR", params$subset.length, folder, c())
```
