---
title: "Results"
author: "Loong Kuan"
date: "16 September 2016"
output: 
  html_document:
    fig_width: 10
    fig_height: 7.5
params:
  file1: "20130505"
  file2: "20131129"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(params$file1, , "_", params$file2,'.html')) })
---

```{r setup, echo = FALSE}
options(width=80)
knitr::opts_chunk$set(echo = FALSE, out.width='750px', dpi=200)
library(knitr)
library(ggplot2)
library(ggrepel)
library(plotly)
library(reshape2)
library(gridExtra)
library(grid)
library(foreign)
read_chunk("../core/visualise_results/result_table.R")
read_chunk("../core/visualise_results/mds.R")
read_chunk("../core/visualisation.R")
read_chunk("../core/visualise_results/heatmaps.R")
read_chunk("../core/visualise_results/detailed_likelihood.R")
read_chunk("../core/visualise_results/detailed_posterior.R")
read_chunk("../core/verification/read_data.R")
read_chunk("../core/verification/compare_distributions.R")
```




## Original Data of 2 Dates
```{r}
<<arff>>
```


<!-- Load the satellite data set on the day *2013-05-05* and *2013-11-29*. -->
<!-- ```{r load_satellite} -->
<!-- file1 <- paste0("../../datasets/train_seed/", params$file1, ".arff") -->
<!-- file2 <- paste0("../../datasets/train_seed/", params$file2, ".arff") -->
<!-- data.all <- ReadArffData(file1, file2) -->
<!-- ``` -->
<!-- Data from *2013-05-05*. -->
<!-- ```{r} -->
<!-- print(head(data.all[[1]], 5)) -->
<!-- ``` -->
<!-- Data from *2013-11-29*. -->
<!-- ```{r} -->
<!-- print(head(data.all[[2]], 5)) -->
<!-- ``` -->

<!-- Histogram of the data by attributes. -->
<!-- ```{r, echo = FALSE} -->
<!-- <<visualisation>> -->
<!-- <<compare>> -->
<!-- ``` -->
<!-- ```{r, echo = FALSE} -->
<!--   Histogram(data.all[[1]], data.all[[2]]) -->
<!-- ``` -->

## Drift Results
The raw data of the results will be provided at the end of this document.
```{r, include=F}
<<results>>
  results.prior.1 <- ResultTable(paste0("../../data_out/train_seed/",
                                        params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                        "1-attributes_covariate.csv"))
  results.prior.2 <- ResultTable(paste0("../../data_out/train_seed/", 
                                        params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                        "2-attributes_covariate.csv"))
  results.prior.3 <- ResultTable(paste0("../../data_out/train_seed/", 
                                        params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                        "3-attributes_covariate.csv"))
  results.cc.1 <- ResultTable(paste0("../../data_out/train_seed/", 
                                     params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                     "1-attributes_likelihood.csv"))
  results.cc.2 <- ResultTable(paste0("../../data_out/train_seed/", 
                                     params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                     "2-attributes_likelihood.csv"))
  results.cc.detailed.1 <- ResultTable(paste0("../../data_out/train_seed/", 
                                              params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                              "1-attributes_likelihood_detailed.csv"))
  results.cc.detailed.2 <- ResultTable(paste0("../../data_out/train_seed/", 
                                              params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                              "2-attributes_likelihood_detailed.csv"))
  results.pos.1 <- ResultTable(paste0("../../data_out/train_seed/", 
                                      params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                      "1-attributes_posterior.csv")) 
  results.pos.2 <- ResultTable(paste0("../../data_out/train_seed/",  
                                      params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                      "2-attributes_posterior.csv"))
  results.pos.3 <- ResultTable(paste0("../../data_out/train_seed/", 
                                      params$file1, "_", params$file2, "/analyse/1_1991977_1991978_3983954/",
                                      "3-attributes_posterior.csv"))
```

-------------------------------------------

### Covariate Drift
The following is the results for a test of 1 Attribute. 
We can verify the correctness of the results by comparing them to the histograms of the attributes above.

```{r}
  #TODO: Use proper arguments
  <<heatmaps>>
  VisualSingleAttribute(results.prior.1, "Covariate")
```

```{r}
  VisualPairAttributes(results.prior.1, results.prior.2, drift.type = "Covariate")
```

Here is a heatmap for 3 attributes that contains the attribute with the highest variance in difference.
```{r}
  VisualTripleAttributes(results.prior.1, results.prior.2, results.prior.3, drift.type = "Covariate")
```

--------------------------------------------------

### Likelihood (Single Attributes)
```{r}
  VisualSingleAttribute(results.cc.1, drift.type = "Likelihood")
```

### Likelihood (Pair Attributes)
```{r, fig.width = 15, fig.height=15}
  VisualPairAttributes(results.cc.1, results.cc.2, drift.type = "Likelihood")
```

### Detailed Likelihood (Single Attributes)
```{r}
  VisualSingleLikelihoodAttribute(results.cc.detailed.1)
```

### Detailed Likelihood (Pair Attributes)
```{r, fig.width = 15, fig.height=15}
  VisualPairLikelihoodAttributes(results.cc.detailed.1, results.cc.detailed.2)
```

---------------------------------------------------------------------------------------------------

### Posterior (1 Attribute)

```{r}
  VisualPairAttributes(results.pos.1, results.pos.2, drift.type = "Posterior")
  VisualTripleAttributes(results.pos.1, results.pos.2, results.pos.3, drift.type = "Posterior")
```

--------------------------------------------------------------------------------

<!-- ### Comparing Results -->
<!-- ```{r, include=F} -->
<!--   results.new.prior.1 <- ResultTable(paste0("../../data_out/train_seed/",  -->
<!--                                             "20131113", "_", params$file2, "/analyse/1_1991977_1991978_3983954/",  -->
<!--                                             "20131113", "_", params$file2, "_1-attributes_covariate.csv")) -->
<!--   results.new.prior.2 <- ResultTable(paste0("../../data_out/train_seed/",  -->
<!--                                             "20131113", "_", params$file2, "/analyse/1_1991977_1991978_3983954/",  -->
<!--                                             "20131113", "_", params$file2, "_2-attributes_covariate.csv")) -->
<!--   results.new.cc.1 <- ResultTable(paste0("../../data_out/train_seed/",  -->
<!--                                             "20131113", "_", params$file2, "/analyse/1_1991977_1991978_3983954/",  -->
<!--                                          "20131113", "_", params$file2, "_1-attributes_likelihood.csv")) -->
<!--   results.new.cc.2 <- ResultTable(paste0("../../data_out/train_seed/",  -->
<!--                                             "20131113", "_", params$file2, "/analyse/1_1991977_1991978_3983954/",  -->
<!--                                          "20131113", "_", params$file2, "_2-attributes_likelihood.csv")) -->
<!--   results.new.cc.detailed.1 <- ResultTable(paste0("../../data_out/train_seed/",  -->
<!--                                             "20131113", "_", params$file2, "/analyse/1_1991977_1991978_3983954/",  -->
<!--                                                   "20131113", "_", params$file2, -->
<!--                                                   "_1-attributes_likelihood_detailed.csv")) -->
<!--   results.new.pos.1 <- ResultTable(paste0("../../data_out/train_seed/",  -->
<!--                                             "20131113", "_", params$file2, "/analyse/1_1991977_1991978_3983954/",  -->
<!--                                           "20131113", "_", params$file2, "_1-attributes_posterior.csv")) -->
<!--   results.new.pos.2 <- ResultTable(paste0("../../data_out/train_seed/",  -->
<!--                                             "20131113", "_", params$file2, "/analyse/1_1991977_1991978_3983954/",  -->
<!--                                           "20131113", "_", params$file2, "_2-attributes_posterior.csv")) -->
<!-- ``` -->

<!-- #### Comparing Covaraite Drift between *20130505 - 20131129* and *20131113 - 20131129*: -->
<!-- ```{r} -->
<!--   compareResults(list(results.prior.1, results.prior.2), list(results.new.prior.1, results.new.prior.2)) -->
<!-- ``` -->

<!-- #### Comparing Likelihood Drift between *20130505 - 20131129* and *20131113 - 20131129*: -->
<!-- ```{r} -->
<!--   compareResults(list(results.cc.1, results.cc.2), list(results.new.cc.1, results.new.cc.2)) -->
<!-- ``` -->

<!-- #### Comparing Posterior Drift between *20130505 - 20131129* and *20131113 - 20131129*: -->
<!-- ```{r} -->
<!--   compareResults(list(results.pos.1, results.pos.2), list(results.new.pos.1, results.new.pos.2)) -->
<!-- ``` -->

<!-- ## Raw Data -->
<!-- https://github.com/LeeLoongKuan/DriftMapper/tree/master/data_out/martvard -->

<!-- ## Raw Plots -->
<!-- https://github.com/LeeLoongKuan/DriftMapper/tree/master/DataAnalysisR/Plots -->


