```{r setup, echo = FALSE, message = FALSE}
library(foreign)
source("../../../core/drift_timeline/timeline.R")
source("../../../core/visualisation.R")
source("../../../core/visualise_results/result_table.R")
source("../../../core/visualise_results/heatmaps.R")
source("../../../core/visualise_results/detailed_likelihood.R")
source("../../../core/visualise_results/detailed_posterior.R")
source("../../../core/verification/compare_distributions.R")
```

```{r electricity, echo = FALSE, message = FALSE, warning = FALSE}
elec <- read.arff("../../../../datasets/elecNormNewClean.arff")
PlotWindowSize("COVARIATE", 30, c(1, 5), "../../../../data_out/elecNormNewClean/moving_chunk/", ymax = 1, x.raw.values = elec[, 1])
PlotWindowSize("JOINT", 30, c(1, 5), "../../../../data_out/elecNormNewClean/moving_chunk/", ymax = 1, x.raw.values = elec[, 1])
PlotWindowSize("LIKELIHOOD", 30, c(1, 5), "../../../../data_out/elecNormNewClean/moving_chunk/", ymax = 1, x.raw.values = elec[, 1])
PlotWindowSize("POSTERIOR", 30, c(1, 5), "../../../../data_out/elecNormNewClean/moving_chunk/", ymax = 1, x.raw.values = elec[, 1])
```


<!-- ```{r airlines, echo = FALSE, message = FALSE, warning = FALSE} -->
<!-- PlotAllWindowSizes("COVARIATE", 1, "../../../../data_out/airlines/moving_chunk/", c(), ymax = 0.25) -->
<!-- PlotAllWindowSizes("LIKELIHOOD", 1, "../../../../data_out/airlines/moving_chunk/", c(), ymax = 0.25) -->
<!-- PlotAllWindowSizes("POSTERIOR", 1, "../../../../data_out/airlines/moving_chunk/", c(), ymax = 0.25) -->
<!-- PlotAllWindowSizes("JOINT", 1, "../../../../data_out/airlines/moving_chunk/", c(), ymax = 0.25) -->
<!-- ``` -->
